# ASP.NET Core
# Build a Web project that uses ASP.NET Core.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# YAML reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  MajorVesion: '1'
  MinorVerion: '0'

resources:
- repo: self

stages:
         
- stage: Nuget
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'Schedule')), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job:
      steps:
      - powershell: |
          [xml] $xdoc = Get-Content "Wiz.Api.Template.Client.nuspec"
          $xdoc.package.metadata.version = "$(MajorVesion).$(MinorVerion).$(Build.BuildId)"
          $xdoc.Save("Wiz.Api.Template.Client.nuspec") 
        displayName: 'PowerShell Script'

      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet >= 5.x'
        inputs:
          versionSpec: '>= 5.x'
          checkLatest: true

      - task: NuGetCommand@2
        displayName: 'NuGet pack'
        inputs:
          command: pack
          packagesToPack: Wiz.Api.Template.Client.nuspec

      - task: NuGetCommand@2
        displayName: 'NuGet pack'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'nuget.org'